[project]
name = "grandtour"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["notebook", "zarr", "matplotlib", "plotly", "rich", "opencv-python", "IPython", "scipy", "imageio", "pathlib"]
